language: node_js
node_js:
  - "8.9.1"

branches:
 only:
  - master

#addons:
  #apt:
    #sources:
      #- ubuntu-toolchain-r-test
    #packages:
      #- openjdk-7-jdk

before_script:
  - npm i npm@latest -g
  - npm install -g ionic cordova
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xvf android-sdk_r24.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-26.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-26
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/26.0.2

script:
  - ionic cordova build android --prod

#deploy:
  #provider: pages
  #skip-cleanup: true
  #github-token: $GITHUB_TOKEN 
  #keep-history: true
  #on:
    #branch: master
  #local_dir: www